// AUTO-GENERATED by scripts/gen-icon-map.mjs — 请勿手改。
// 新增图标后重跑:  node scripts/gen-icon-map.mjs
// 深度导入单图标文件绕过 lucide-react barrel,让打包器只保留用到的图标。
import Activity from "lucide-react/dist/esm/icons/activity.mjs";
import AlertCircle from "lucide-react/dist/esm/icons/alert-circle.mjs";
import AlertOctagon from "lucide-react/dist/esm/icons/alert-octagon.mjs";
import AlertTriangle from "lucide-react/dist/esm/icons/alert-triangle.mjs";
import ArrowLeft from "lucide-react/dist/esm/icons/arrow-left.mjs";
import ArrowRight from "lucide-react/dist/esm/icons/arrow-right.mjs";
import BadgeCheck from "lucide-react/dist/esm/icons/badge-check.mjs";
import Ban from "lucide-react/dist/esm/icons/ban.mjs";
import BarChart3 from "lucide-react/dist/esm/icons/bar-chart-3.mjs";
import Bell from "lucide-react/dist/esm/icons/bell.mjs";
import BookOpen from "lucide-react/dist/esm/icons/book-open.mjs";
import Bot from "lucide-react/dist/esm/icons/bot.mjs";
import Briefcase from "lucide-react/dist/esm/icons/briefcase.mjs";
import Building2 from "lucide-react/dist/esm/icons/building-2.mjs";
import Calendar from "lucide-react/dist/esm/icons/calendar.mjs";
import CalendarCheck from "lucide-react/dist/esm/icons/calendar-check.mjs";
import CalendarDays from "lucide-react/dist/esm/icons/calendar-days.mjs";
import CalendarPlus from "lucide-react/dist/esm/icons/calendar-plus.mjs";
import CalendarX from "lucide-react/dist/esm/icons/calendar-x.mjs";
import Check from "lucide-react/dist/esm/icons/check.mjs";
import CheckCheck from "lucide-react/dist/esm/icons/check-check.mjs";
import CheckCircle from "lucide-react/dist/esm/icons/check-circle.mjs";
import CheckCircle2 from "lucide-react/dist/esm/icons/check-circle-2.mjs";
import ChevronDown from "lucide-react/dist/esm/icons/chevron-down.mjs";
import ChevronLeft from "lucide-react/dist/esm/icons/chevron-left.mjs";
import ChevronRight from "lucide-react/dist/esm/icons/chevron-right.mjs";
import ChevronUp from "lucide-react/dist/esm/icons/chevron-up.mjs";
import ChevronsDownUp from "lucide-react/dist/esm/icons/chevrons-down-up.mjs";
import ChevronsUpDown from "lucide-react/dist/esm/icons/chevrons-up-down.mjs";
import ClipboardCheck from "lucide-react/dist/esm/icons/clipboard-check.mjs";
import ClipboardPlus from "lucide-react/dist/esm/icons/clipboard-plus.mjs";
import ClipboardX from "lucide-react/dist/esm/icons/clipboard-x.mjs";
import Clock from "lucide-react/dist/esm/icons/clock.mjs";
import Cloud from "lucide-react/dist/esm/icons/cloud.mjs";
import Copy from "lucide-react/dist/esm/icons/copy.mjs";
import CornerDownRight from "lucide-react/dist/esm/icons/corner-down-right.mjs";
import CornerUpLeft from "lucide-react/dist/esm/icons/corner-up-left.mjs";
import DollarSign from "lucide-react/dist/esm/icons/dollar-sign.mjs";
import Dot from "lucide-react/dist/esm/icons/dot.mjs";
import Download from "lucide-react/dist/esm/icons/download.mjs";
import DownloadCloud from "lucide-react/dist/esm/icons/download-cloud.mjs";
import Edit3 from "lucide-react/dist/esm/icons/edit-3.mjs";
import ExternalLink from "lucide-react/dist/esm/icons/external-link.mjs";
import Eye from "lucide-react/dist/esm/icons/eye.mjs";
import EyeOff from "lucide-react/dist/esm/icons/eye-off.mjs";
import File from "lucide-react/dist/esm/icons/file.mjs";
import FileSignature from "lucide-react/dist/esm/icons/file-signature.mjs";
import FileText from "lucide-react/dist/esm/icons/file-text.mjs";
import FileUp from "lucide-react/dist/esm/icons/file-up.mjs";
import Files from "lucide-react/dist/esm/icons/files.mjs";
import Filter from "lucide-react/dist/esm/icons/filter.mjs";
import Flame from "lucide-react/dist/esm/icons/flame.mjs";
import Folder from "lucide-react/dist/esm/icons/folder.mjs";
import FolderKanban from "lucide-react/dist/esm/icons/folder-kanban.mjs";
import Gift from "lucide-react/dist/esm/icons/gift.mjs";
import Globe from "lucide-react/dist/esm/icons/globe.mjs";
import GraduationCap from "lucide-react/dist/esm/icons/graduation-cap.mjs";
import GripVertical from "lucide-react/dist/esm/icons/grip-vertical.mjs";
import HeartPulse from "lucide-react/dist/esm/icons/heart-pulse.mjs";
import Hourglass from "lucide-react/dist/esm/icons/hourglass.mjs";
import Image from "lucide-react/dist/esm/icons/image.mjs";
import Inbox from "lucide-react/dist/esm/icons/inbox.mjs";
import Info from "lucide-react/dist/esm/icons/info.mjs";
import KeyRound from "lucide-react/dist/esm/icons/key-round.mjs";
import Laptop from "lucide-react/dist/esm/icons/laptop.mjs";
import LayoutDashboard from "lucide-react/dist/esm/icons/layout-dashboard.mjs";
import LayoutTemplate from "lucide-react/dist/esm/icons/layout-template.mjs";
import LineChart from "lucide-react/dist/esm/icons/line-chart.mjs";
import Link from "lucide-react/dist/esm/icons/link.mjs";
import Link2 from "lucide-react/dist/esm/icons/link-2.mjs";
import Link2Off from "lucide-react/dist/esm/icons/link-2-off.mjs";
import ListChecks from "lucide-react/dist/esm/icons/list-checks.mjs";
import ListTree from "lucide-react/dist/esm/icons/list-tree.mjs";
import Loader from "lucide-react/dist/esm/icons/loader.mjs";
import Lock from "lucide-react/dist/esm/icons/lock.mjs";
import LogIn from "lucide-react/dist/esm/icons/log-in.mjs";
import LogOut from "lucide-react/dist/esm/icons/log-out.mjs";
import Mail from "lucide-react/dist/esm/icons/mail.mjs";
import MapPin from "lucide-react/dist/esm/icons/map-pin.mjs";
import Menu from "lucide-react/dist/esm/icons/menu.mjs";
import MessageCircle from "lucide-react/dist/esm/icons/message-circle.mjs";
import MessageSquare from "lucide-react/dist/esm/icons/message-square.mjs";
import MessageSquarePlus from "lucide-react/dist/esm/icons/message-square-plus.mjs";
import Minus from "lucide-react/dist/esm/icons/minus.mjs";
import Moon from "lucide-react/dist/esm/icons/moon.mjs";
import MoreHorizontal from "lucide-react/dist/esm/icons/more-horizontal.mjs";
import Network from "lucide-react/dist/esm/icons/network.mjs";
import Paperclip from "lucide-react/dist/esm/icons/paperclip.mjs";
import PenLine from "lucide-react/dist/esm/icons/pen-line.mjs";
import Pencil from "lucide-react/dist/esm/icons/pencil.mjs";
import Phone from "lucide-react/dist/esm/icons/phone.mjs";
import Plus from "lucide-react/dist/esm/icons/plus.mjs";
import PlusCircle from "lucide-react/dist/esm/icons/plus-circle.mjs";
import QrCode from "lucide-react/dist/esm/icons/qr-code.mjs";
import Quote from "lucide-react/dist/esm/icons/quote.mjs";
import RefreshCw from "lucide-react/dist/esm/icons/refresh-cw.mjs";
import Repeat from "lucide-react/dist/esm/icons/repeat.mjs";
import Reply from "lucide-react/dist/esm/icons/reply.mjs";
import RotateCcw from "lucide-react/dist/esm/icons/rotate-ccw.mjs";
import Route from "lucide-react/dist/esm/icons/route.mjs";
import Save from "lucide-react/dist/esm/icons/save.mjs";
import ScrollText from "lucide-react/dist/esm/icons/scroll-text.mjs";
import Search from "lucide-react/dist/esm/icons/search.mjs";
import SearchCheck from "lucide-react/dist/esm/icons/search-check.mjs";
import Send from "lucide-react/dist/esm/icons/send.mjs";
import Settings2 from "lucide-react/dist/esm/icons/settings-2.mjs";
import Share2 from "lucide-react/dist/esm/icons/share-2.mjs";
import Shield from "lucide-react/dist/esm/icons/shield.mjs";
import ShieldCheck from "lucide-react/dist/esm/icons/shield-check.mjs";
import ShieldOff from "lucide-react/dist/esm/icons/shield-off.mjs";
import Smartphone from "lucide-react/dist/esm/icons/smartphone.mjs";
import Sparkles from "lucide-react/dist/esm/icons/sparkles.mjs";
import Star from "lucide-react/dist/esm/icons/star.mjs";
import Stethoscope from "lucide-react/dist/esm/icons/stethoscope.mjs";
import StickyNote from "lucide-react/dist/esm/icons/sticky-note.mjs";
import Target from "lucide-react/dist/esm/icons/target.mjs";
import ThumbsDown from "lucide-react/dist/esm/icons/thumbs-down.mjs";
import ThumbsUp from "lucide-react/dist/esm/icons/thumbs-up.mjs";
import Trash2 from "lucide-react/dist/esm/icons/trash-2.mjs";
import TrendingDown from "lucide-react/dist/esm/icons/trending-down.mjs";
import TrendingUp from "lucide-react/dist/esm/icons/trending-up.mjs";
import Trophy from "lucide-react/dist/esm/icons/trophy.mjs";
import Upload from "lucide-react/dist/esm/icons/upload.mjs";
import UploadCloud from "lucide-react/dist/esm/icons/upload-cloud.mjs";
import User from "lucide-react/dist/esm/icons/user.mjs";
import UserCheck from "lucide-react/dist/esm/icons/user-check.mjs";
import UserCircle from "lucide-react/dist/esm/icons/user-circle.mjs";
import UserCog from "lucide-react/dist/esm/icons/user-cog.mjs";
import UserPlus from "lucide-react/dist/esm/icons/user-plus.mjs";
import Users from "lucide-react/dist/esm/icons/users.mjs";
import UsersRound from "lucide-react/dist/esm/icons/users-round.mjs";
import Video from "lucide-react/dist/esm/icons/video.mjs";
import Vote from "lucide-react/dist/esm/icons/vote.mjs";
import X from "lucide-react/dist/esm/icons/x.mjs";
import XCircle from "lucide-react/dist/esm/icons/x-circle.mjs";
import Zap from "lucide-react/dist/esm/icons/zap.mjs";

export const ICON_MAP = {
  "activity": Activity,
  "alert-circle": AlertCircle,
  "alert-octagon": AlertOctagon,
  "alert-triangle": AlertTriangle,
  "arrow-left": ArrowLeft,
  "arrow-right": ArrowRight,
  "badge-check": BadgeCheck,
  "ban": Ban,
  "bar-chart-3": BarChart3,
  "bell": Bell,
  "book-open": BookOpen,
  "bot": Bot,
  "briefcase": Briefcase,
  "building-2": Building2,
  "calendar": Calendar,
  "calendar-check": CalendarCheck,
  "calendar-days": CalendarDays,
  "calendar-plus": CalendarPlus,
  "calendar-x": CalendarX,
  "check": Check,
  "check-check": CheckCheck,
  "check-circle": CheckCircle,
  "check-circle-2": CheckCircle2,
  "chevron-down": ChevronDown,
  "chevron-left": ChevronLeft,
  "chevron-right": ChevronRight,
  "chevron-up": ChevronUp,
  "chevrons-down-up": ChevronsDownUp,
  "chevrons-up-down": ChevronsUpDown,
  "clipboard-check": ClipboardCheck,
  "clipboard-plus": ClipboardPlus,
  "clipboard-x": ClipboardX,
  "clock": Clock,
  "cloud": Cloud,
  "copy": Copy,
  "corner-down-right": CornerDownRight,
  "corner-up-left": CornerUpLeft,
  "dollar-sign": DollarSign,
  "dot": Dot,
  "download": Download,
  "download-cloud": DownloadCloud,
  "edit-3": Edit3,
  "external-link": ExternalLink,
  "eye": Eye,
  "eye-off": EyeOff,
  "file": File,
  "file-signature": FileSignature,
  "file-text": FileText,
  "file-up": FileUp,
  "files": Files,
  "filter": Filter,
  "flame": Flame,
  "folder": Folder,
  "folder-kanban": FolderKanban,
  "gift": Gift,
  "globe": Globe,
  "graduation-cap": GraduationCap,
  "grip-vertical": GripVertical,
  "heart-pulse": HeartPulse,
  "hourglass": Hourglass,
  "image": Image,
  "inbox": Inbox,
  "info": Info,
  "key-round": KeyRound,
  "laptop": Laptop,
  "layout-dashboard": LayoutDashboard,
  "layout-template": LayoutTemplate,
  "line-chart": LineChart,
  "link": Link,
  "link-2": Link2,
  "link-2-off": Link2Off,
  "list-checks": ListChecks,
  "list-tree": ListTree,
  "loader": Loader,
  "lock": Lock,
  "log-in": LogIn,
  "log-out": LogOut,
  "mail": Mail,
  "map-pin": MapPin,
  "menu": Menu,
  "message-circle": MessageCircle,
  "message-square": MessageSquare,
  "message-square-plus": MessageSquarePlus,
  "minus": Minus,
  "moon": Moon,
  "more-horizontal": MoreHorizontal,
  "network": Network,
  "paperclip": Paperclip,
  "pen-line": PenLine,
  "pencil": Pencil,
  "phone": Phone,
  "plus": Plus,
  "plus-circle": PlusCircle,
  "qr-code": QrCode,
  "quote": Quote,
  "refresh-cw": RefreshCw,
  "repeat": Repeat,
  "reply": Reply,
  "rotate-ccw": RotateCcw,
  "route": Route,
  "save": Save,
  "scroll-text": ScrollText,
  "search": Search,
  "search-check": SearchCheck,
  "send": Send,
  "settings-2": Settings2,
  "share-2": Share2,
  "shield": Shield,
  "shield-check": ShieldCheck,
  "shield-off": ShieldOff,
  "smartphone": Smartphone,
  "sparkles": Sparkles,
  "star": Star,
  "stethoscope": Stethoscope,
  "sticky-note": StickyNote,
  "target": Target,
  "thumbs-down": ThumbsDown,
  "thumbs-up": ThumbsUp,
  "trash-2": Trash2,
  "trending-down": TrendingDown,
  "trending-up": TrendingUp,
  "trophy": Trophy,
  "upload": Upload,
  "upload-cloud": UploadCloud,
  "user": User,
  "user-check": UserCheck,
  "user-circle": UserCircle,
  "user-cog": UserCog,
  "user-plus": UserPlus,
  "users": Users,
  "users-round": UsersRound,
  "video": Video,
  "vote": Vote,
  "x": X,
  "x-circle": XCircle,
  "zap": Zap,
};
