// Seeded candidate records based on uploads/简历_简历_总览.csv schema.
// In the real product, these come from the LLM-parsed resume pipeline (Kimi/DeepSeek).

window.MESA_CANDIDATES = [
  {
    id: 'c-001',
    name: '郝福强',
    gender: 'male',
    animal: 'dog',
    avatar: null,
    education: '硕士',
    school: '合肥工业大学',
    major: '工业工程',
    age: 41,
    location: '安徽·合肥',
    yearsExp: 19,
    phone: '134-8570-6423',
    email: '9659478@qq.com',
    appliedFor: '海外产品质量',
    jdMatch: 85,
    status: '面试中',
    source: '自动上传',
    pushedAt: '2026-03-01',
    parser: 'Kimi',
    parserConfidence: 92,
    tags: ['海外项目', '焊接工艺', 'PMP', '8D/FMEA', '高级工程师'],
    skills: [
      '9 年车身焊接工艺工程经验与零部件质量管理经验',
      '6 年海外项目开发与管理经验（巴西 / 中东 / 韩国）',
      '熟练应用 CATIA、CAPP、SOLID3000',
      'PMP 项目管理课程学习，机械工程高级工程师',
      '熟悉 8D、FMEA 等质量工具',
    ],
    risks: [
      '邮箱为 QQ 邮箱，职业专业度不足',
      '工作年限 19 年但仅展示 3 段工作单位，可能存在时间断档',
      '期望年薪 40W/年，与新能源行业匹配度待评估',
      '缺乏具体量化业绩数据（成本节约 / 效率提升 %）',
      '海外项目经验但未标注语言能力',
    ],
    highlights: [
      '完整新能源汽车产业链经验：江淮 + 吉利 + 蔚来',
      '稀缺海外项目经验：巴西、中东、韩国三地市场',
      '技术 + 管理复合背景，从工艺工程转项目管理',
      '学术成果丰富：16 项专利、3 篇论文',
      '蔚来内部认证：Navi L1、Terminator L1、年度 PIM Star',
    ],
    experience: [
      { period: '2023.2 – 至今', company: '蔚来汽车科技（安徽）', title: 'PIM 主任工程师', summary: '负责 ET5/ES6/Blanc 车身零部件工业化与全生命周期质量管理。' },
      { period: '2021.11 – 2023.2', company: '吉利汽车集团', title: '高级项目经理（韩国 RSM 合资）', summary: '负责 R745 车型韩国合资项目整体管理。' },
      { period: '2016.5 – 2021.11', company: '安徽江淮汽车', title: '主任工程师（中东市场地产化）', summary: 'T8/S7/S5/S3/J4 五款车型中东市场零部件地产化开发。' },
      { period: '2013.5 – 2014.12', company: '安徽江淮汽车', title: '焊接工艺主管工程师（巴西合资）', summary: '巴西合资项目焊装工艺方案制定与实施。' },
    ],
    educationHistory: [
      { period: '2009.1 – 2011.12', school: '合肥工业大学', major: '工业工程', degree: '硕士' },
      { period: '2002.9 – 2006.7', school: '太原理工大学', major: '机械设计制造及其自动化', degree: '本科' },
    ],
    attachment: '1-个人简历-郝福强20250628.docx',
  },
  {
    id: 'c-002',
    name: '郑宝伟',
    gender: 'male',
    animal: 'turtle',
    avatar: null,
    education: '本科',
    school: '新疆大学',
    major: '材料科学与工程',
    age: 40,
    location: '陕西·宝鸡',
    yearsExp: 16,
    phone: '132-8961-8962',
    email: 'qiantian2918@163.com',
    appliedFor: '海外产品质量',
    jdMatch: 78,
    status: '已沟通',
    source: '猎头',
    pushedAt: '2026-03-04',
    parser: 'DeepSeek',
    parserConfidence: 88,
    tags: ['6Sigma', '8D', 'IATF16949', '三坐标测量', '团队管理'],
    skills: [
      '质量工具：6Sigma、8D、5WHY、SPC、MSA、FMEA、CP、PPAP、APQP',
      '质量管理体系：IATF16949、ISO9001',
      '数字化工具：PowerBI、FineBI、QuickBI、低代码',
      '测量技术：三坐标、激光跟踪仪、PC-DMIS 高级认证',
      '无损检测资质：射线 Ⅰ 级、超声 Ⅱ 级、磁粉 Ⅱ 级',
    ],
    risks: [
      '简历无量化工作成果（金额 / 缺陷率 / 团队规模）',
      '无项目经验专项模块，项目成果分散',
      '2011.1 – 2011.4 存在 3 个月空档期',
      '无外语能力 / 期望薪资 / 离职原因说明',
    ],
    highlights: [
      '覆盖入厂检验、项目质量、复合解析、测量四大模块',
      '传统质量工具 + 数字化能力兼具',
      'PC-DMIS 高级认证，全国技术比武奖项',
      '丰富团队管理与人员培训经验',
    ],
    experience: [
      { period: '2017.10 – 至今', company: '宝鸡吉利汽车部件', title: '零部件检验科长 / 项目质量经理 / 测量主管', summary: '从测量主管成长到检验科长，覆盖入厂检验、项目质量策划、复合解析。' },
      { period: '2011.4 – 2017.10', company: '佛吉亚（广州）汽车部件', title: '过程质量 / 客户质量 / 测量工程师', summary: '过程质量改进、客户质量问题处理、三坐标测量编程。' },
      { period: '2008.3 – 2011.1', company: '新疆科瑞检测科技', title: '无损检测工程师', summary: '无损检测方案编制与报告。' },
    ],
    educationHistory: [
      { period: '2002.9 – 2006.7', school: '新疆大学', major: '材料科学与工程', degree: '本科' },
    ],
    attachment: '郑宝伟-简历-202603.pdf',
  },
  {
    id: 'c-003',
    name: '陈思琪',
    gender: 'female',
    animal: 'rabbit',
    avatar: '../../assets/avatars/avatar7.png',
    education: '硕士',
    school: '同济大学',
    major: '车辆工程',
    age: 32,
    location: '上海·浦东',
    yearsExp: 9,
    phone: '189-2233-1124',
    email: 'chensq.engineer@outlook.com',
    appliedFor: '智能驾驶感知工程师',
    jdMatch: 93,
    status: '待入职',
    source: '内推',
    pushedAt: '2026-04-02',
    parser: 'Kimi',
    parserConfidence: 95,
    tags: ['BEV 感知', 'PyTorch', 'C++', 'Apollo', '激光雷达', '同济硕士'],
    skills: [
      '5 年 BEV / Occupancy 感知算法量产经验',
      'PyTorch / C++ / CUDA，熟悉 Apollo、自研感知栈',
      '激光雷达 + 多目融合，前后处理优化',
      '主导 2 款量产车型感知模块从 SOP 到 OTA',
      '英语 CET-6，能阅读英文论文与文档',
    ],
    risks: [
      '5 年内 3 家公司，平均在职 18 个月',
      '期望薪资上浮 35%，需与 HRBP 二次确认',
    ],
    highlights: [
      '蔚来 ET7 / 小鹏 P7 量产感知主力贡献者',
      '同济车辆 + 智能交通双背景',
      '团队骨干，曾带 4 人小组负责 Occupancy 模块',
      'CVPR Workshop 论文一作',
    ],
    experience: [
      { period: '2023.6 – 至今', company: '小鹏汽车 XNGP', title: '高级感知算法工程师', summary: 'XNet 2.0 Occupancy 网络优化，量产部署。' },
      { period: '2021.3 – 2023.6', company: '蔚来 NIO Autonomous Driving', title: '感知算法工程师', summary: 'ET7 多目融合与车道线检测。' },
      { period: '2017.7 – 2021.3', company: '上汽集团前瞻技术研究院', title: '感知算法工程师', summary: '激光雷达点云分割、前端预处理。' },
    ],
    educationHistory: [
      { period: '2015.9 – 2017.6', school: '同济大学', major: '车辆工程', degree: '硕士' },
      { period: '2011.9 – 2015.6', school: '同济大学', major: '车辆工程', degree: '本科' },
    ],
    attachment: '陈思琪-感知-202604.pdf',
  },
  {
    id: 'c-004',
    name: '王嘉伟',
    gender: 'male',
    animal: 'bear',
    avatar: null,
    education: '本科',
    school: '北京理工大学',
    major: '机械工程',
    age: 28,
    location: '北京·亦庄',
    yearsExp: 5,
    phone: '186-1100-7765',
    email: 'wangjw@bit.edu.cn',
    appliedFor: '车身工艺工程师',
    jdMatch: 68,
    status: '待筛选',
    source: 'BOSS 直聘',
    pushedAt: '2026-05-08',
    parser: 'Kimi',
    parserConfidence: 89,
    tags: ['CATIA', '焊接', '夹具设计', '初级'],
    skills: [
      '3 年车身焊接夹具设计与调试',
      '熟练 CATIA、AutoCAD',
      '熟悉 GD&T、夹具定位原理',
      '一汽-大众实习 6 个月',
    ],
    risks: [
      '工作年限不足岗位要求（要求 5+，实际 3 年量产经验）',
      '未独立负责过整车级项目',
      '无海外项目经验',
    ],
    highlights: [
      '北理工本硕基础扎实',
      '熟悉主流车企焊装流程',
      '稳定性好，5 年仅 1 段工作经历',
    ],
    experience: [
      { period: '2021.7 – 至今', company: '北汽新能源', title: '车身工艺工程师', summary: '极狐 αT 焊装夹具开发与调试。' },
    ],
    educationHistory: [
      { period: '2017.9 – 2021.6', school: '北京理工大学', major: '机械工程', degree: '本科' },
    ],
    attachment: '王嘉伟-车身-202605.pdf',
  },
  {
    id: 'c-005',
    name: '刘晓萌',
    gender: 'female',
    animal: 'bird',
    avatar: null,
    education: '硕士',
    school: '哈尔滨工业大学',
    major: '控制科学与工程',
    age: 30,
    location: '深圳·南山',
    yearsExp: 7,
    phone: '139-2266-0011',
    email: 'liu.xm@hit.edu.cn',
    appliedFor: '电池管理系统工程师',
    jdMatch: 91,
    status: '面试中',
    source: '官网',
    pushedAt: '2026-04-22',
    parser: 'DeepSeek',
    parserConfidence: 93,
    tags: ['BMS', 'MATLAB/Simulink', 'AUTOSAR', '宁德时代'],
    skills: [
      '5 年 BMS 软件开发与标定',
      'MATLAB/Simulink、AUTOSAR、UDS、ISO 26262',
      '电池建模 + SOC/SOH 算法量产经验',
      '负责 2 款量产电池包 BMS 软件',
    ],
    risks: [
      '当前职级偏低（专员），需确认 leveling',
    ],
    highlights: [
      '宁德时代 + 比亚迪双 BMS 量产背景',
      'ISO 26262 功能安全完整流程经验',
      '哈工大控制硕士，理论基础扎实',
    ],
    experience: [
      { period: '2023.3 – 至今', company: '比亚迪 弗迪电池', title: 'BMS 高级软件工程师', summary: '海豹 / 海豚 BMS 软件量产。' },
      { period: '2019.7 – 2023.3', company: '宁德时代', title: 'BMS 软件工程师', summary: '乘用车电池包 BMS 算法开发。' },
    ],
    educationHistory: [
      { period: '2017.9 – 2019.6', school: '哈尔滨工业大学', major: '控制科学与工程', degree: '硕士' },
    ],
    attachment: '刘晓萌-BMS-202604.pdf',
  },
  {
    id: 'c-006',
    name: '徐文博',
    gender: 'male',
    animal: 'squirrel',
    avatar: '../../assets/avatars/avatar4.png',
    education: '硕士',
    school: '清华大学',
    major: '汽车工程',
    age: 35,
    location: '北京·海淀',
    yearsExp: 12,
    phone: '138-0013-4288',
    email: 'xuwb@thsigma.com',
    appliedFor: '智能座舱总监',
    jdMatch: 88,
    status: '已沟通',
    source: '猎头',
    pushedAt: '2026-04-15',
    parser: 'Kimi',
    parserConfidence: 91,
    tags: ['座舱', '团队管理', 'HMI', '量产负责人'],
    skills: [
      '12 年智能座舱量产经验，3 款量产车型',
      '管理过 22 人跨职能团队',
      '熟悉高通 8155 / 8295 平台',
      '主导座舱-车控-云端一体化架构',
    ],
    risks: [
      '近期跳槽频繁，3 年内 2 次',
      '期望薪资 80W + 期权，预算敏感',
    ],
    highlights: [
      '清华汽车硕士，2 篇 SAE 论文',
      '理想 L9 / 蔚来 ET7 座舱核心贡献者',
      '具备 0-1 与 1-10 双重经验',
    ],
    experience: [
      { period: '2024.3 – 至今', company: '理想汽车', title: '智能座舱负责人', summary: '统筹 L 系列座舱体验与平台演进。' },
      { period: '2019.5 – 2024.3', company: '蔚来 NIO', title: '座舱平台高级经理', summary: 'ET7 / ES7 座舱量产。' },
    ],
    educationHistory: [
      { period: '2011.9 – 2014.6', school: '清华大学', major: '汽车工程', degree: '硕士' },
    ],
    attachment: '徐文博-座舱总监-202604.pdf',
  },
  {
    id: 'c-007',
    name: '李慧',
    gender: 'female',
    animal: 'cat',
    avatar: null,
    education: '本科',
    school: '武汉理工大学',
    major: '工业设计',
    age: 27,
    location: '杭州·余杭',
    yearsExp: 4,
    phone: '155-8899-1100',
    email: 'lihui.design@gmail.com',
    appliedFor: 'HMI 交互设计师',
    jdMatch: 81,
    status: '已沟通',
    source: 'BOSS 直聘',
    pushedAt: '2026-05-02',
    parser: 'Kimi',
    parserConfidence: 90,
    tags: ['HMI', 'Figma', '车机 UX', '设计系统'],
    skills: [
      '4 年车机 HMI 设计，2 款量产车型',
      'Figma、Sketch、ProtoPie',
      '主导设计系统从 0 到 1',
      '熟悉 8295 平台多屏交互',
    ],
    risks: [
      '工业设计本科背景，缺少正式 UX 训练',
      '作品集偏新势力风格，传统主机厂适配待评估',
    ],
    highlights: [
      '哪吒 / 零跑 量产车机 HMI 主力',
      '主导建立公司级车机设计系统',
      '红点设计奖入围 1 次',
    ],
    experience: [
      { period: '2024.2 – 至今', company: '零跑汽车', title: 'HMI 高级设计师', summary: 'C16 车机 HMI 与设计系统。' },
      { period: '2022.7 – 2024.2', company: '哪吒汽车', title: 'HMI 设计师', summary: 'S 系列车机交互。' },
    ],
    educationHistory: [
      { period: '2018.9 – 2022.6', school: '武汉理工大学', major: '工业设计', degree: '本科' },
    ],
    attachment: '李慧-HMI-202605.pdf',
  },
  {
    id: 'c-008',
    name: '黄启航',
    gender: 'male',
    animal: 'rat',
    avatar: null,
    education: '博士',
    school: '上海交通大学',
    major: '电力电子',
    age: 36,
    location: '上海·闵行',
    yearsExp: 10,
    phone: '136-7788-0099',
    email: 'huang.qh@sjtu.edu.cn',
    appliedFor: '电驱系统专家',
    jdMatch: 96,
    status: '已入职',
    source: '内推',
    pushedAt: '2026-02-18',
    parser: 'Kimi',
    parserConfidence: 97,
    tags: ['电驱', 'SiC', 'PhD', '专利 14 项'],
    skills: [
      '10 年电驱系统与功率电子量产经验',
      '熟悉 SiC、IGBT 模块设计与控制',
      '主导 800V 平台电驱量产',
      '14 项发明专利，3 篇 IEEE TIE',
    ],
    risks: [],
    highlights: [
      '交大博士，国家重点研发项目核心成员',
      '小鹏 G9 / 智己 LS6 电驱核心贡献者',
      '行业稀缺 SiC 量产经验',
    ],
    experience: [
      { period: '2020.4 – 至今', company: '智己汽车', title: '电驱系统专家', summary: 'LS6 / L7 电驱量产。' },
      { period: '2015.9 – 2020.4', company: '联合电子', title: '高级工程师', summary: '电机控制器开发。' },
    ],
    educationHistory: [
      { period: '2011.9 – 2015.6', school: '上海交通大学', major: '电力电子', degree: '博士' },
    ],
    attachment: '黄启航-电驱-博士-202602.pdf',
  },
  {
    id: 'c-009',
    name: '吴佳怡',
    gender: 'female',
    animal: 'fish',
    avatar: null,
    education: '本科',
    school: '同济大学',
    major: '会计学',
    age: 25,
    location: '上海·徐汇',
    yearsExp: 3,
    phone: '177-2299-3344',
    email: 'wujiayi.acct@163.com',
    appliedFor: '财务分析师',
    jdMatch: 42,
    status: '已淘汰',
    source: '自动上传',
    pushedAt: '2026-05-09',
    parser: 'DeepSeek',
    parserConfidence: 86,
    tags: ['会计', '审计', '初级'],
    skills: [
      '3 年四大审计经验',
      'CPA 全科通过',
      'Excel / Power Query 熟练',
    ],
    risks: [
      '无主机厂行业经验',
      '岗位为财务分析，候选人偏审计方向',
      '岗位需求 5 年经验',
    ],
    highlights: [
      '同济会计 + CPA 全科',
      '四大背景，工作严谨',
    ],
    experience: [
      { period: '2022.7 – 至今', company: '普华永道（上海）', title: '审计高级专员', summary: 'A 股制造业客户审计。' },
    ],
    educationHistory: [
      { period: '2018.9 – 2022.6', school: '同济大学', major: '会计学', degree: '本科' },
    ],
    attachment: '吴佳怡-财务-202605.pdf',
  },
  {
    id: 'c-010',
    name: '张子轩',
    gender: 'unknown',
    animal: 'snail',
    avatar: null,
    education: '硕士',
    school: '浙江大学',
    major: '计算机科学',
    age: 29,
    location: '杭州·西湖',
    yearsExp: 6,
    phone: '152-0099-8877',
    email: 'zhangzx@zju.edu.cn',
    appliedFor: '云平台架构师',
    jdMatch: 87,
    status: '待筛选',
    source: 'BOSS 直聘',
    pushedAt: '2026-05-12',
    parser: 'Kimi',
    parserConfidence: 92,
    tags: ['K8s', 'Go', '云原生', '阿里 P7'],
    skills: [
      '6 年云原生 / 微服务架构',
      'Go / Rust、K8s、Service Mesh',
      '主导集团云迁移项目',
      'AWS / 阿里云双栈',
    ],
    risks: [
      '无汽车行业经验',
      '当前 P7，目标岗位为架构师，level 需评估',
    ],
    highlights: [
      '浙大 CS 硕士',
      '阿里巴巴中间件团队 P7',
      'GitHub 开源项目 2.3k+ stars',
    ],
    experience: [
      { period: '2020.5 – 至今', company: '阿里巴巴 中间件', title: '高级开发工程师 P7', summary: '集团云原生中间件建设。' },
      { period: '2018.7 – 2020.5', company: '字节跳动', title: '后端工程师', summary: '业务后端 + 基础架构。' },
    ],
    educationHistory: [
      { period: '2016.9 – 2018.6', school: '浙江大学', major: '计算机科学', degree: '硕士' },
    ],
    attachment: '张子轩-云架构-202605.pdf',
  },
  {
    id: 'c-011',
    name: '孙韵竹',
    gender: 'female',
    animal: 'bug',
    avatar: null,
    education: '硕士',
    school: '北京航空航天大学',
    major: '机械电子工程',
    age: 31,
    location: '北京·昌平',
    yearsExp: 8,
    phone: '131-4477-2200',
    email: 'sun.yz@buaa.edu.cn',
    appliedFor: '底盘域控软件经理',
    jdMatch: 84,
    status: '面试中',
    source: '内推',
    pushedAt: '2026-04-10',
    parser: 'DeepSeek',
    parserConfidence: 91,
    tags: ['底盘', 'AUTOSAR', '团队管理', '北航硕士'],
    skills: [
      '8 年底盘控制软件开发',
      '熟悉 ESC / EPS / 主动悬挂',
      '团队管理 6 人',
      'ISO 26262 ASIL-D 完整流程',
    ],
    risks: [
      '管理经验偏短（1.5 年）',
    ],
    highlights: [
      '北航机电硕士',
      '理想 L9 主动悬挂量产负责人',
      '具备硬件 + 软件 + 整车标定全栈视角',
    ],
    experience: [
      { period: '2023.1 – 至今', company: '理想汽车', title: '底盘软件经理', summary: 'L 系列主动悬挂软件。' },
      { period: '2018.7 – 2023.1', company: '蔚来 NIO', title: '底盘软件工程师', summary: 'ET7 / ES8 ESC 软件。' },
    ],
    educationHistory: [
      { period: '2016.9 – 2018.6', school: '北京航空航天大学', major: '机械电子工程', degree: '硕士' },
    ],
    attachment: '孙韵竹-底盘-202604.pdf',
  },
  {
    id: 'c-012',
    name: '马天宇',
    gender: 'male',
    animal: 'worm',
    avatar: null,
    education: '本科',
    school: '华中科技大学',
    major: '电气工程',
    age: 33,
    location: '武汉·光谷',
    yearsExp: 11,
    phone: '187-5566-1100',
    email: 'matianyu@huawei.com',
    appliedFor: '高压系统工程师',
    jdMatch: 73,
    status: '已沟通',
    source: '官网',
    pushedAt: '2026-04-28',
    parser: 'Kimi',
    parserConfidence: 88,
    tags: ['高压', '电气安全', '量产'],
    skills: [
      '11 年高压电气系统经验',
      '熟悉高压互锁、绝缘检测',
      '主导 3 款量产车型高压架构',
    ],
    risks: [
      '近 5 年仅 1 段工作经历，能力广度待评估',
      '本科学历，部分岗位要求硕士',
    ],
    highlights: [
      '华为车 BU 高压资深工程师',
      '问界 M9 高压架构核心贡献者',
    ],
    experience: [
      { period: '2018.10 – 至今', company: '华为 智能汽车解决方案 BU', title: '高级工程师', summary: '问界 M5 / M9 高压系统。' },
      { period: '2013.7 – 2018.10', company: '东风岚图', title: '电气工程师', summary: '岚图 FREE 高压系统。' },
    ],
    educationHistory: [
      { period: '2009.9 – 2013.6', school: '华中科技大学', major: '电气工程', degree: '本科' },
    ],
    attachment: '马天宇-高压-202604.pdf',
  },
];

window.MESA_JOBS = [
  { id: 'j-001', title: '海外产品质量', dept: '质量·海外', owner: '李薇', openings: 2, candidates: 28, level: 'P7–P8', location: '合肥', urgency: 'high', updatedAt: '2026-05-13' },
  { id: 'j-002', title: '智能驾驶感知工程师', dept: '智驾·感知', owner: '王浩', openings: 3, candidates: 41, level: 'P6–P7', location: '上海', urgency: 'high', updatedAt: '2026-05-12' },
  { id: 'j-003', title: '电池管理系统工程师', dept: '三电·BMS', owner: '陈璐', openings: 2, candidates: 22, level: 'P6–P7', location: '深圳', urgency: 'mid', updatedAt: '2026-05-11' },
  { id: 'j-004', title: '智能座舱总监', dept: '智舱', owner: '张磊', openings: 1, candidates: 9, level: 'M3', location: '北京', urgency: 'high', updatedAt: '2026-05-10' },
  { id: 'j-005', title: '车身工艺工程师', dept: '车身·工艺', owner: '吴敏', openings: 4, candidates: 51, level: 'P5–P6', location: '北京', urgency: 'mid', updatedAt: '2026-05-09' },
  { id: 'j-006', title: 'HMI 交互设计师', dept: '设计·HMI', owner: '陈璐', openings: 1, candidates: 17, level: 'P6', location: '杭州', urgency: 'low', updatedAt: '2026-05-09' },
  { id: 'j-007', title: '电驱系统专家', dept: '三电·电驱', owner: '李薇', openings: 1, candidates: 6, level: 'P8', location: '上海', urgency: 'high', updatedAt: '2026-05-08' },
  { id: 'j-008', title: '底盘域控软件经理', dept: '底盘', owner: '王浩', openings: 1, candidates: 12, level: 'M2', location: '北京', urgency: 'mid', updatedAt: '2026-05-07' },
];

window.MESA_STATUS_ORDER = ['待筛选', '已沟通', '面试中', '待定中', '待入职', '已入职', '已淘汰'];

// ─────────────────────── Post-hire lifecycle ───────────────────────
window.MESA_HIRE_STAGES = ['待入职', '入职准备', '入职当天', '试用期', '已转正', '延期试用', '已离职'];

window.MESA_HIRE_STAGE_TONE = {
  '待入职':   { bg: '#FFEDD5', fg: '#9A3412', dot: '#F97316' },
  '入职准备': { bg: '#FEF3C7', fg: '#854D0E', dot: '#EAB308' },
  '入职当天': { bg: '#E9E3FF', fg: '#2111A5', dot: '#422AFB' },
  '试用期':   { bg: '#DBEAFE', fg: '#1D4ED8', dot: '#3B82F6' },
  '已转正':   { bg: '#DCFCE7', fg: '#15803D', dot: '#22C55E' },
  '延期试用': { bg: '#FEF3C7', fg: '#92400E', dot: '#F59E0B' },
  '已离职':   { bg: '#FEE2E2', fg: '#B91C1C', dot: '#F53939' },
};

window.MESA_TASK_STATUS_TONE = {
  '已完成':   { bg: '#DCFCE7', fg: '#15803D', dot: '#22C55E', icon: 'check' },
  '进行中':   { bg: '#DBEAFE', fg: '#1D4ED8', dot: '#3B82F6', icon: 'loader' },
  '待开始':   { bg: '#F4F7FE', fg: '#707EAE', dot: '#A3AED0', icon: 'clock' },
  '已逾期':   { bg: '#FEE2E2', fg: '#B91C1C', dot: '#F53939', icon: 'alert-triangle' },
  '不适用':   { bg: '#F8F9FA', fg: '#A3AED0', dot: '#CBD5E0', icon: 'minus' },
};

// Seed employees — candidates who already crossed the 待入职 / 已入职 line,
// plus a few more for the full lifecycle range.
window.MESA_EMPLOYEES = [
  {
    id: 'E-0003', candidateId: 'c-003', name: '陈思琪', gender: 'female', animal: 'rabbit',
    avatar: '../../assets/avatars/avatar7.png',
    education: '硕士', school: '同济大学', major: '车辆工程', age: 32, location: '上海·浦东',
    yearsExp: 9, phone: '189-2233-1124', email: 'chensq.engineer@outlook.com',
    appliedFor: '智能驾驶感知工程师', jobId: 'j-002', dept: '智驾·感知', jdOwner: '王浩',
    level: 'P6–P7', workLocation: '上海', jdMatch: 93,
    stage: '入职准备',
    plannedHireDate: '2026-06-01', actualHireDate: null, probationEndDate: '2026-08-30',
    regularizeDate: null, regularizeAdvice: '待定',
    hrbp: '陈璐', directManager: '王浩',
    checklist: {
      offer:    { status: '已完成', date: '2026-05-14', owner: '李薇',  note: '候选人已签字回传' },
      bgCheck:  { status: '已完成', date: '2026-05-18', owner: '李薇',  note: '三方背调通过' },
      medical:  { status: '进行中', date: '—',         owner: '陈璐',  note: '已发体检函,待预约' },
      materials:{ status: '进行中', date: '—',         owner: '陈思琪', note: '身份证 / 学历认证已提交,离职证明缺' },
      account:  { status: '待开始', date: '—',         owner: 'IT',    note: '入职日 D-3 自动创建' },
      equipment:{ status: '待开始', date: '—',         owner: 'IT',    note: 'MacBook Pro 16 / 显示器待领用' },
      training: { status: '待开始', date: '—',         owner: 'L&D',   note: '新员工训练营 6/3–6/5' },
    },
    probation: {
      day30: { date: '2026-07-01', status: '待开始', notes: '' },
      day60: { date: '2026-07-31', status: '待开始', notes: '' },
      day90: { date: '2026-08-30', status: '待开始', notes: '', completion: null },
    },
    events: [
      { date: '2026-05-14', type: 'Offer', title: 'Offer 已签字', desc: '候选人接受 Offer · 年薪 78W + 期权', owner: '李薇' },
      { date: '2026-05-09', type: '招聘', title: '通过终面', desc: '感知方向终面通过,JD 匹配度 93/100', owner: '王浩' },
    ],
    risks: [
      { item: '5 年内 3 家公司,平均在职 18 个月', level: '中', source: 'AI风险项', owner: '陈璐 (HRBP)', action: '入职前再访谈一次,确认动机与长期规划', dueDate: '2026-05-28', status: '进行中' },
      { item: '期望薪资上浮 35%,需与 HRBP 二次确认', level: '中', source: 'AI风险项', owner: '陈璐 (HRBP)', action: '薪资 Letter 已签,关闭', dueDate: '2026-05-12', status: '已完成' },
    ],
    parser: 'Kimi', parserConfidence: 95, source: '内推', attachment: '陈思琪-感知-202604.pdf',
    tags: ['BEV 感知', 'PyTorch', '同济硕士'],
  },
  {
    id: 'E-0008', candidateId: 'c-008', name: '黄启航', gender: 'male', animal: 'rat',
    avatar: null,
    education: '博士', school: '上海交通大学', major: '电力电子', age: 36, location: '上海·闵行',
    yearsExp: 10, phone: '136-7788-0099', email: 'huang.qh@sjtu.edu.cn',
    appliedFor: '电驱系统专家', jobId: 'j-007', dept: '三电·电驱', jdOwner: '李薇',
    level: 'P8', workLocation: '上海', jdMatch: 96,
    stage: '试用期',
    plannedHireDate: '2026-03-15', actualHireDate: '2026-03-17', probationEndDate: '2026-06-15',
    regularizeDate: null, regularizeAdvice: '建议转正',
    hrbp: '陈璐', directManager: '李薇',
    checklist: {
      offer:    { status: '已完成', date: '2026-02-20', owner: '李薇', note: 'Offer 签字 · 年薪 110W + 期权' },
      bgCheck:  { status: '已完成', date: '2026-02-28', owner: '李薇', note: '通过' },
      medical:  { status: '已完成', date: '2026-03-05', owner: '陈璐', note: '合格' },
      materials:{ status: '已完成', date: '2026-03-10', owner: '黄启航', note: '全部齐全' },
      account:  { status: '已完成', date: '2026-03-15', owner: 'IT',   note: '邮箱 / VPN / Gitlab 全开通' },
      equipment:{ status: '已完成', date: '2026-03-17', owner: 'IT',   note: 'MacBook Pro M3 Max · 已领用' },
      training: { status: '已完成', date: '2026-03-19', owner: 'L&D',  note: '新员工训练营完成' },
    },
    probation: {
      day30: { date: '2026-04-16', status: '已完成', notes: '快速融入团队,SiC 项目立项推进良好' },
      day60: { date: '2026-05-16', status: '已完成', notes: 'OKR 进度 75%,已主导 1 次内部技术分享' },
      day90: { date: '2026-06-15', status: '进行中', notes: '准备 90 天评估材料', completion: 0.82 },
    },
    events: [
      { date: '2026-05-12', type: '关键项目', title: '主导 800V 电驱平台 v2.0 立项',     desc: '已发起需求评审,跨部门 6 人协同', owner: '李薇' },
      { date: '2026-04-22', type: '培训',     title: '完成新员工训练营 · 评分 A',      desc: '导师评价积极',                owner: 'L&D' },
      { date: '2026-04-16', type: '试用期',   title: '30 天访谈 · 适应良好',           desc: '与团队磨合顺畅,无显著阻力', owner: '陈璐' },
      { date: '2026-03-17', type: '入职',     title: '入职 电驱系统专家',              desc: 'JD 匹配度 96/100 · 来源 内推', owner: '李薇' },
    ],
    risks: [
      { item: '暂无显著风险项', level: '低', source: 'AI风险项', owner: '—', action: '观察期', dueDate: '—', status: '无需跟进' },
    ],
    parser: 'Kimi', parserConfidence: 97, source: '内推', attachment: '黄启航-电驱-博士-202602.pdf',
    tags: ['电驱', 'SiC', '专利 14 项'],
  },
  {
    id: 'E-0011', candidateId: null, name: '赵明远', gender: 'male', animal: 'turtle',
    avatar: '../../assets/avatars/avatar2.png',
    education: '硕士', school: '西安交通大学', major: '车辆工程', age: 33, location: '北京·亦庄',
    yearsExp: 8, phone: '139-1100-2244', email: 'zhao.my@example.com',
    appliedFor: '底盘域控软件经理', jobId: 'j-008', dept: '底盘', jdOwner: '王浩',
    level: 'M2', workLocation: '北京', jdMatch: 89,
    stage: '试用期',
    plannedHireDate: '2026-04-01', actualHireDate: '2026-04-07', probationEndDate: '2026-07-07',
    regularizeDate: null, regularizeAdvice: '待定',
    hrbp: '陈璐', directManager: '王浩',
    checklist: {
      offer: { status: '已完成', date: '2026-03-08', owner: '李薇', note: '已签字' },
      bgCheck: { status: '已完成', date: '2026-03-18', owner: '李薇', note: '通过' },
      medical: { status: '已完成', date: '2026-03-22', owner: '陈璐', note: '合格' },
      materials: { status: '已完成', date: '2026-04-01', owner: '赵明远', note: '齐全' },
      account: { status: '已完成', date: '2026-04-07', owner: 'IT', note: '已开通' },
      equipment: { status: '已完成', date: '2026-04-07', owner: 'IT', note: '已领用' },
      training: { status: '已完成', date: '2026-04-12', owner: 'L&D', note: '通过' },
    },
    probation: {
      day30: { date: '2026-05-07', status: '已完成', notes: '前 30 天熟悉团队和代码库,节奏偏慢' },
      day60: { date: '2026-06-06', status: '进行中', notes: '上级反馈技术方案推进略迟,需 HRBP 介入', completion: 0.55 },
      day90: { date: '2026-07-06', status: '待开始', notes: '', completion: null },
    },
    events: [
      { date: '2026-05-13', type: '关键项目', title: 'L9 主动悬挂软件 v3 进度 50%', desc: '完成接口对齐,余下 6 周冲刺', owner: '王浩' },
      { date: '2026-04-07', type: '入职', title: '入职 底盘域控软件经理', desc: 'JD 匹配度 89/100', owner: '李薇' },
    ],
    risks: [
      { item: '60 天 OKR 进度仅 55%,低于预期', level: '中', source: 'HRBP观察', owner: '王浩', action: '每周 1-1,梳理任务优先级', dueDate: '2026-06-15', status: '进行中' },
      { item: '管理经验偏短(1.5 年)',         level: '低', source: 'AI风险项', owner: '陈璐 (HRBP)', action: '安排管理培训',                  dueDate: '2026-07-01', status: '待开始' },
    ],
    parser: 'DeepSeek', parserConfidence: 88, source: '内推', attachment: '赵明远-底盘-202603.pdf',
    tags: ['底盘', 'AUTOSAR', '团队管理'],
  },
  {
    id: 'E-0012', candidateId: null, name: '李欣怡', gender: 'female', animal: 'bird',
    avatar: '../../assets/avatars/avatar3.png',
    education: '硕士', school: '浙江大学', major: '人机交互', age: 28, location: '杭州·西湖',
    yearsExp: 5, phone: '155-2200-9988', email: 'li.xy@example.com',
    appliedFor: 'HMI 交互设计师', jobId: 'j-006', dept: '设计·HMI', jdOwner: '陈璐',
    level: 'P6', workLocation: '杭州', jdMatch: 86,
    stage: '已转正',
    plannedHireDate: '2025-11-03', actualHireDate: '2025-11-03', probationEndDate: '2026-02-02',
    regularizeDate: '2026-02-02', regularizeAdvice: '已转正',
    hrbp: '陈璐', directManager: '陈璐',
    checklist: { offer: { status: '已完成' }, bgCheck: { status: '已完成' }, medical: { status: '已完成' }, materials: { status: '已完成' }, account: { status: '已完成' }, equipment: { status: '已完成' }, training: { status: '已完成' } },
    probation: {
      day30: { date: '2025-12-03', status: '已完成', notes: '快速融入,作品集风格切换顺利' },
      day60: { date: '2026-01-02', status: '已完成', notes: 'OKR 完成 80%' },
      day90: { date: '2026-02-02', status: '已完成', notes: '完成 2 款车型 HMI 改版,转正', completion: 0.92 },
    },
    events: [
      { date: '2026-04-10', type: '关键项目', title: '主导 X-Series 新车机 HMI 设计', desc: '完成视觉稿评审',  owner: '陈璐' },
      { date: '2026-02-02', type: '转正',     title: '正式转正',                       desc: '试用期完成度 92%', owner: '陈璐' },
      { date: '2025-11-03', type: '入职',     title: '入职 HMI 交互设计师',            desc: 'JD 匹配度 86/100', owner: '李薇' },
    ],
    risks: [],
    parser: 'Kimi', parserConfidence: 92, source: '官网', attachment: '李欣怡-HMI-202510.pdf',
    tags: ['HMI', 'Figma', '车机 UX'],
  },
  {
    id: 'E-0013', candidateId: null, name: '周浩', gender: 'male', animal: 'bear',
    avatar: '../../assets/avatars/avatar5.png',
    education: '本科', school: '武汉大学', major: '电子信息工程', age: 35, location: '北京·亦庄',
    yearsExp: 12, phone: '186-9988-5511', email: 'zhou.hao@example.com',
    appliedFor: '车身工艺工程师', jobId: 'j-005', dept: '车身·工艺', jdOwner: '吴敏',
    level: 'P7', workLocation: '北京', jdMatch: 81,
    stage: '已转正',
    plannedHireDate: '2024-05-20', actualHireDate: '2024-05-20', probationEndDate: '2024-08-18',
    regularizeDate: '2024-08-18', regularizeAdvice: '已转正',
    hrbp: '陈璐', directManager: '吴敏',
    checklist: { offer: { status: '已完成' }, bgCheck: { status: '已完成' }, medical: { status: '已完成' }, materials: { status: '已完成' }, account: { status: '已完成' }, equipment: { status: '已完成' }, training: { status: '已完成' } },
    probation: {
      day30: { date: '2024-06-19', status: '已完成', notes: '快速融入' },
      day60: { date: '2024-07-19', status: '已完成', notes: '推进焊装方案优化' },
      day90: { date: '2024-08-18', status: '已完成', notes: '转正,带教 2 名新人', completion: 0.95 },
    },
    events: [
      { date: '2026-03-12', type: '晋升', title: '晋升 P7 → 高级工程师 P8',       desc: '年度评审 A+',                     owner: '吴敏' },
      { date: '2025-09-08', type: '关键项目', title: '主导新平台焊装工艺标准',     desc: '横向跨 3 个项目',                 owner: '吴敏' },
      { date: '2024-08-18', type: '转正', title: '正式转正',                       desc: '试用期完成度 95%',               owner: '陈璐' },
      { date: '2024-05-20', type: '入职', title: '入职 车身工艺工程师',           desc: 'JD 匹配度 81/100',               owner: '李薇' },
    ],
    risks: [],
    parser: 'Kimi', parserConfidence: 88, source: '猎头', attachment: '周浩-车身-202404.pdf',
    tags: ['焊接', 'CATIA', '工艺标准'],
  },
  {
    id: 'E-0014', candidateId: null, name: '王思雨', gender: 'female', animal: 'cat',
    avatar: '../../assets/avatars/avatar11.png',
    education: '硕士', school: '南京大学', major: '计算机科学', age: 27, location: '深圳·南山',
    yearsExp: 3, phone: '177-3344-0099', email: 'wang.sy@example.com',
    appliedFor: '电池管理系统工程师', jobId: 'j-003', dept: '三电·BMS', jdOwner: '陈璐',
    level: 'P5', workLocation: '深圳', jdMatch: 76,
    stage: '入职当天',
    plannedHireDate: '2026-05-15', actualHireDate: '2026-05-15', probationEndDate: '2026-08-13',
    regularizeDate: null, regularizeAdvice: '待定',
    hrbp: '陈璐', directManager: '陈璐',
    checklist: {
      offer: { status: '已完成', date: '2026-04-20', owner: '李薇', note: '已签字' },
      bgCheck: { status: '已完成', date: '2026-04-28', owner: '李薇', note: '通过' },
      medical: { status: '已完成', date: '2026-05-05', owner: '陈璐', note: '合格' },
      materials: { status: '已完成', date: '2026-05-15', owner: '王思雨', note: '齐全' },
      account: { status: '进行中', date: '2026-05-15', owner: 'IT', note: '今日开通中' },
      equipment: { status: '进行中', date: '2026-05-15', owner: 'IT', note: '设备发放中' },
      training: { status: '待开始', date: '2026-05-18', owner: 'L&D', note: '本周训练营' },
    },
    probation: {
      day30: { date: '2026-06-14', status: '待开始', notes: '' },
      day60: { date: '2026-07-14', status: '待开始', notes: '' },
      day90: { date: '2026-08-13', status: '待开始', notes: '', completion: null },
    },
    events: [
      { date: '2026-05-15', type: '入职', title: '入职 电池管理系统工程师', desc: 'JD 匹配度 76/100 · 今日 Day 1', owner: '李薇' },
    ],
    risks: [
      { item: '工作年限 3 年低于 JD 要求(5 年)', level: '中', source: 'AI风险项', owner: '陈璐 (HRBP)', action: '安排资深带教 2 个月', dueDate: '2026-07-15', status: '进行中' },
    ],
    parser: 'DeepSeek', parserConfidence: 87, source: 'BOSS 直聘', attachment: '王思雨-BMS-202604.pdf',
    tags: ['BMS', 'Python', 'MATLAB'],
  },
];

window.MESA_HIRE_CHECKLIST_KEYS = [
  { key: 'offer',     label: 'Offer 签署',  icon: 'file-signature' },
  { key: 'bgCheck',   label: '背景调查',     icon: 'search-check' },
  { key: 'medical',   label: '入职体检',     icon: 'stethoscope' },
  { key: 'materials', label: '入职材料',     icon: 'files' },
  { key: 'account',   label: '账号开通',     icon: 'user-check' },
  { key: 'equipment', label: '设备发放',     icon: 'laptop' },
  { key: 'training',  label: '新员工培训',   icon: 'graduation-cap' },
];

// Tenured staff — already past probation, the bulk of "现有人员".
// Lightweight records: enough for directory + click-through to detail.
const TENURED_TEMPLATE = (stub) => ({
  candidateId: null,
  level: stub.level || 'P6',
  workLocation: stub.location?.split('·')[0] || '上海',
  jobId: stub.jobId || null,
  jdMatch: stub.jdMatch || 80,
  stage: '已转正',
  plannedHireDate: stub.hireDate,
  actualHireDate: stub.hireDate,
  probationEndDate: stub.regularizeDate || stub.hireDate,
  regularizeDate: stub.regularizeDate || stub.hireDate,
  regularizeAdvice: '已转正',
  hrbp: stub.hrbp || '陈璐',
  checklist: { offer: { status: '已完成' }, bgCheck: { status: '已完成' }, medical: { status: '已完成' }, materials: { status: '已完成' }, account: { status: '已完成' }, equipment: { status: '已完成' }, training: { status: '已完成' } },
  probation: {
    day30: { date: '—', status: '已完成', notes: '已完成' },
    day60: { date: '—', status: '已完成', notes: '已完成' },
    day90: { date: stub.regularizeDate || '—', status: '已完成', notes: '已转正', completion: 0.9 },
  },
  events: stub.events || [
    { date: stub.hireDate, type: '入职', title: `入职 ${stub.appliedFor}`, desc: `JD 匹配度 ${stub.jdMatch || 80}/100`, owner: '李薇' },
  ],
  risks: [],
  parser: 'Kimi', parserConfidence: 90,
  source: stub.source || '社招',
  attachment: '—',
  tags: stub.tags || [],
  ...stub,
});

window.MESA_EMPLOYEES = window.MESA_EMPLOYEES.concat([
  TENURED_TEMPLATE({
    id: 'E-0015', name: '吴敏', gender: 'female', animal: 'fish', avatar: '../../assets/avatars/avatar9.png',
    education: '硕士', school: '同济大学', major: '机械工程', age: 38, location: '北京·亦庄', yearsExp: 14,
    phone: '139-1100-3344', email: 'wu.min@mesa.app',
    appliedFor: '车身工艺经理', dept: '车身·工艺', jdOwner: '李薇', jobId: 'j-005', level: 'M2',
    hireDate: '2022-03-14', regularizeDate: '2022-06-12',
    directManager: '李薇', source: '猎头', jdMatch: 92,
    tags: ['焊接工艺', '团队管理', '海外项目'],
    events: [
      { date: '2025-09-12', type: '晋升', title: '晋升为车身工艺经理 (M2)', desc: '年度评审 A+', owner: '李薇' },
      { date: '2024-05-08', type: '关键项目', title: '主导新平台焊装方案', desc: '横向 4 个项目',  owner: '李薇' },
      { date: '2022-03-14', type: '入职', title: '入职 车身工艺工程师 P7', desc: '社招',              owner: '李薇' },
    ],
  }),
  TENURED_TEMPLATE({
    id: 'E-0016', name: '张磊', gender: 'male', animal: 'dog', avatar: '../../assets/avatars/avatar4.png',
    education: '硕士', school: '清华大学', major: '计算机科学', age: 39, location: '北京·海淀', yearsExp: 16,
    phone: '136-2299-0011', email: 'zhang.lei@mesa.app',
    appliedFor: '智驾感知总监', dept: '智驾·感知', jdOwner: '李薇', jobId: 'j-002', level: 'M3',
    hireDate: '2021-08-02', regularizeDate: '2021-11-01',
    directManager: '李薇', source: '内推', jdMatch: 95,
    tags: ['智能驾驶', '团队管理', '架构师'],
  }),
  TENURED_TEMPLATE({
    id: 'E-0017', name: '陈璐', gender: 'female', animal: 'rabbit', avatar: '../../assets/avatars/avatar7.png',
    education: '本科', school: '北京师范大学', major: '人力资源管理', age: 34, location: '北京·朝阳', yearsExp: 11,
    phone: '152-9933-0011', email: 'chen.lu@mesa.app',
    appliedFor: 'HRBP', dept: 'HR · HRBP', jdOwner: '李薇', jobId: null, level: 'P7',
    hireDate: '2022-09-05', regularizeDate: '2022-12-04',
    directManager: '李薇', source: '官网', jdMatch: 88,
    tags: ['HRBP', '员工关系', '招聘'],
  }),
  TENURED_TEMPLATE({
    id: 'E-0018', name: '王浩', gender: 'male', animal: 'bear', avatar: '../../assets/avatars/avatar8.png',
    education: '硕士', school: '北京航空航天大学', major: '飞行器设计', age: 37, location: '北京·昌平', yearsExp: 13,
    phone: '186-2200-3344', email: 'wang.hao@mesa.app',
    appliedFor: '智驾经理', dept: '智驾·感知', jdOwner: '张磊', jobId: 'j-002', level: 'M2',
    hireDate: '2023-04-10', regularizeDate: '2023-07-09',
    directManager: '张磊', source: '猎头', jdMatch: 90,
    tags: ['智驾', '量产', '团队管理'],
  }),
  TENURED_TEMPLATE({
    id: 'E-0019', name: '林子璇', gender: 'female', animal: 'cat', avatar: '../../assets/avatars/avatar1.png',
    education: '硕士', school: '复旦大学', major: '应用数学', age: 30, location: '上海·浦东', yearsExp: 6,
    phone: '139-7788-2200', email: 'lin.zx@mesa.app',
    appliedFor: '感知算法工程师', dept: '智驾·感知', jdOwner: '王浩', jobId: 'j-002', level: 'P6',
    hireDate: '2024-02-19', regularizeDate: '2024-05-18',
    directManager: '王浩', source: '内推', jdMatch: 85,
    tags: ['CV', 'PyTorch', '量产'],
  }),
  TENURED_TEMPLATE({
    id: 'E-0020', name: '郑明远', gender: 'male', animal: 'squirrel', avatar: '../../assets/avatars/avatar6.png',
    education: '硕士', school: '上海交通大学', major: '电力电子', age: 33, location: '上海·闵行', yearsExp: 9,
    phone: '136-4477-0099', email: 'zheng.my@mesa.app',
    appliedFor: 'BMS 软件工程师', dept: '三电·BMS', jdOwner: '陈璐', jobId: 'j-003', level: 'P6',
    hireDate: '2024-08-13', regularizeDate: '2024-11-12',
    directManager: '陈璐', source: '社招', jdMatch: 84,
    tags: ['BMS', 'AUTOSAR'],
  }),
  TENURED_TEMPLATE({
    id: 'E-0021', name: '孙晓彤', gender: 'female', animal: 'bird', avatar: '../../assets/avatars/avatar10.png',
    education: '本科', school: '浙江大学', major: '工业设计', age: 29, location: '杭州·西湖', yearsExp: 6,
    phone: '155-3322-1188', email: 'sun.xt@mesa.app',
    appliedFor: 'UX 设计师', dept: '设计·HMI', jdOwner: '陈璐', jobId: 'j-006', level: 'P6',
    hireDate: '2023-11-06', regularizeDate: '2024-02-04',
    directManager: '陈璐', source: 'BOSS 直聘', jdMatch: 82,
    tags: ['UX', 'Figma', '车机'],
  }),
  TENURED_TEMPLATE({
    id: 'E-0022', name: '何思源', gender: 'male', animal: 'turtle', avatar: '../../assets/avatars/avatar5.png',
    education: '博士', school: '清华大学', major: '汽车工程', age: 41, location: '上海·浦东', yearsExp: 16,
    phone: '186-0011-2233', email: 'he.sy@mesa.app',
    appliedFor: '智能座舱总监', dept: '智舱', jdOwner: '李薇', jobId: 'j-004', level: 'M3',
    hireDate: '2021-05-17', regularizeDate: '2021-08-15',
    directManager: '李薇', source: '猎头', jdMatch: 94,
    tags: ['座舱', 'HMI', '团队管理'],
  }),
  TENURED_TEMPLATE({
    id: 'E-0023', name: '黄静怡', gender: 'female', animal: 'rabbit', avatar: '../../assets/avatars/avatar11.png',
    education: '硕士', school: '武汉大学', major: '车辆工程', age: 31, location: '深圳·南山', yearsExp: 7,
    phone: '177-2244-3399', email: 'huang.jy@mesa.app',
    appliedFor: '底盘软件工程师', dept: '底盘', jdOwner: '王浩', jobId: 'j-008', level: 'P6',
    hireDate: '2023-07-24', regularizeDate: '2023-10-22',
    directManager: '王浩', source: '官网', jdMatch: 80,
    tags: ['底盘', 'ESC'],
  }),
  TENURED_TEMPLATE({
    id: 'E-0024', name: '李薇', gender: 'female', animal: 'cat', avatar: '../../assets/avatars/avatar4.png',
    education: '硕士', school: '复旦大学', major: '工商管理', age: 36, location: '北京·朝阳', yearsExp: 13,
    phone: '138-0013-4001', email: 'liwei@mesa.app',
    appliedFor: '高级招聘经理', dept: 'HR · 招聘组', jdOwner: '—', jobId: null, level: 'M2',
    hireDate: '2020-06-08', regularizeDate: '2020-09-06',
    directManager: '—', source: '内推', jdMatch: 96,
    tags: ['招聘', '团队管理', 'AI 招聘'],
  }),
]);

window.MESA_STATUS_TONE = {
  '待筛选':   { bg: '#EDF2F7', fg: '#707EAE', dot: '#707EAE' },
  '已沟通':   { bg: '#DBEAFE', fg: '#1D4ED8', dot: '#3B82F6' },
  '面试中':   { bg: '#E9E3FF', fg: '#2111A5', dot: '#422AFB' },
  '待定中':   { bg: '#FEF3C7', fg: '#854D0E', dot: '#EAB308' },
  '待入职':   { bg: '#FFEDD5', fg: '#9A3412', dot: '#F97316' },
  '已入职':   { bg: '#DCFCE7', fg: '#15803D', dot: '#22C55E' },
  '已淘汰':   { bg: '#FEE2E2', fg: '#B91C1C', dot: '#F53939' },
};

// ─────────────────────── Department directory ───────────────────────
// R&D departments sourced from 部门架构.xlsx; HR retained from prior structure.
window.MESA_DEPARTMENTS = [
  // ── R&D top-level (14 from xlsx) ──
  { id: 'd-101', name: '智驾',                 parentId: null, head: '张磊',   hrbp: '陈璐', location: '北京 · 上海',  founded: '2020', status: 'active', desc: '智能驾驶,覆盖感知 / 规控 / 标定与量产部署。' },
  { id: 'd-102', name: '智舱',                 parentId: null, head: '何思源', hrbp: '陈璐', location: '上海',          founded: '2021', status: 'active', desc: '智能座舱平台、HMI、中控架构与多屏交互。' },
  { id: 'd-103', name: '智慧能源技术中心',     parentId: null, head: '李薇',   hrbp: '陈璐', location: '上海 · 深圳',  founded: '2019', status: 'active', desc: '电池 / 电驱 / 电控,800V 平台与 SiC 量产。' },
  { id: 'd-104', name: '整车验证和工程中心',   parentId: null, head: '吴敏',   hrbp: '陈璐', location: '合肥 · 北京',  founded: '2017', status: 'active', desc: '整车工程、试验试制、量产前验证。' },
  { id: 'd-104a', name: '验证',                parentId: 'd-104', head: '吴敏', hrbp: '陈璐', location: '合肥',          founded: '2017', status: 'active', desc: '整车试验、可靠性测试、属地适应性路试。' },
  { id: 'd-104b', name: '整车技师 (R&D)',      parentId: 'd-104', head: '吴敏', hrbp: '陈璐', location: '合肥',          founded: '2019', status: 'active', desc: 'Master / Vehicle Technician,R&D 试制车技师团队。' },
  { id: 'd-105', name: '底盘',                 parentId: null, head: '王浩',   hrbp: '陈璐', location: '北京',          founded: '2021', status: 'active', desc: '主动悬挂、ESC、EPS 软件与整车标定。' },
  { id: 'd-106', name: '数字架构',             parentId: null, head: '张磊',   hrbp: '陈璐', location: '北京 · 上海',  founded: '2022', status: 'active', desc: '整车 EE 架构、SOA、车云一体化与中间件。' },
  { id: 'd-107', name: '内饰',                 parentId: null, head: '陈璐',   hrbp: '陈璐', location: '上海',          founded: '2020', status: 'active', desc: '内饰造型、人因工程与材料工艺。' },
  { id: 'd-108', name: '热管理',               parentId: null, head: '黄启航', hrbp: '陈璐', location: '上海',          founded: '2020', status: 'active', desc: '整车热管理系统、冷媒回路与水路集成。' },
  { id: 'd-109', name: '车身',                 parentId: null, head: '吴敏',   hrbp: '陈璐', location: '北京 · 合肥',  founded: '2018', status: 'active', desc: 'BIW / 焊装 / 涂装 / 总装工艺。' },
  { id: 'd-110', name: '研发运营',             parentId: null, head: '李薇',   hrbp: '陈璐', location: '上海',          founded: '2019', status: 'active', desc: '研发流程、PMO、工具链与数据治理。' },
  { id: 'd-110a', name: '项目管理 (PMO)',      parentId: 'd-110', head: '李薇', hrbp: '陈璐', location: '上海',          founded: '2019', status: 'active', desc: 'Carline / T1TP 等整车级项目集管理。' },
  { id: 'd-110b', name: '运营管理',            parentId: 'd-110', head: '李薇', hrbp: '陈璐', location: '上海',          founded: '2020', status: 'active', desc: '研发预算、资源、流程与体系治理。' },
  { id: 'd-111', name: '预研',                 parentId: null, head: '何思源', hrbp: '陈璐', location: '上海',          founded: '2021', status: 'active', desc: '前沿技术预研、专利布局与学术合作。' },
  { id: 'd-112', name: '开阳实验室',           parentId: null, head: '张磊',   hrbp: '陈璐', location: '北京',          founded: '2023', status: 'active', desc: '面向下一代智驾的算法与硬件实验室。' },
  { id: 'd-113', name: '外饰',                 parentId: null, head: '陈璐',   hrbp: '陈璐', location: '上海',          founded: '2020', status: 'active', desc: '外饰造型、空气动力学与表面工艺。' },
  { id: 'd-114', name: '智能化中心',           parentId: null, head: '张磊',   hrbp: '陈璐', location: '北京 · 上海',  founded: '2022', status: 'active', desc: '跨域智能化集成、OTA、整车智能体验。' },
  // ── 海外研究院 (NEW) ──
  { id: 'd-200', name: '海外研究院',           parentId: null, head: '李薇',   hrbp: '陈璐', location: '合肥 · 慕尼黑', founded: '2022', status: 'active', desc: '面向海外市场的研发、质量、认证与合规。' },
  { id: 'd-201', name: '海外产品质量',         parentId: 'd-200', head: '李薇', hrbp: '陈璐', location: '合肥',          founded: '2022', status: 'active', desc: '海外整车产品质量管理、属地路试问题闭环。' },
  { id: 'd-202', name: '海外认证',             parentId: 'd-200', head: '李薇', hrbp: '陈璐', location: '慕尼黑',        founded: '2022', status: 'active', desc: '海外法规认证 (EU / UNECE / 中东 / 拉美)。' },
  { id: 'd-203', name: '海外智能化',           parentId: 'd-200', head: '张磊', hrbp: '陈璐', location: '上海 · 慕尼黑', founded: '2023', status: 'active', desc: '海外智能驾驶 / 座舱本地化与功能适配。' },
  { id: 'd-204', name: 'GDPR · 海外合规',     parentId: 'd-200', head: '陈璐', hrbp: '陈璐', location: '慕尼黑',        founded: '2023', status: 'active', desc: '海外数据合规 (GDPR / CCPA),隐私架构。' },
  // ── 产品规划 (NEW) ──
  { id: 'd-300', name: '产品规划',             parentId: null, head: '何思源', hrbp: '陈璐', location: '上海',          founded: '2020', status: 'active', desc: '车型产品定义、研发端 PM、需求落地。' },
  { id: 'd-301', name: '产品定义',             parentId: 'd-300', head: '何思源', hrbp: '陈璐', location: '上海',         founded: '2020', status: 'active', desc: '车型概念、用户场景与卖点定义。' },
  { id: 'd-302', name: '研发端产品经理',       parentId: 'd-300', head: '何思源', hrbp: '陈璐', location: '上海',         founded: '2021', status: 'active', desc: 'R&D 端产品经理,衔接产品定义与工程实现。' },
  // ── HR (retained) ──
  { id: 'd-015', name: 'HR',                  parentId: null,    head: '李薇',   hrbp: '李薇', location: '北京',          founded: '2017', status: 'active', desc: '人力资源,招聘 / HRBP / OD / 培训。' },
  { id: 'd-016', name: '招聘组',               parentId: 'd-015', head: '李薇',   hrbp: '李薇', location: '北京',          founded: '2017', status: 'active', desc: 'AI 招聘 + 技术猎头 + 校园招聘。' },
  { id: 'd-017', name: 'HRBP',                parentId: 'd-015', head: '陈璐',   hrbp: '陈璐', location: '北京 · 上海',  founded: '2018', status: 'active', desc: '业务伙伴,跨部门人才与组织发展。' },
];

// Map legacy dept strings → new department names for backward compat.
window.MESA_DEPT_MIGRATION = {
  '智驾·感知':      '智驾',
  '智驾 · 感知':    '智驾',
  '三电·BMS':       '智慧能源技术中心',
  '三电 · BMS':     '智慧能源技术中心',
  '三电·电驱':      '智慧能源技术中心',
  '三电 · 电驱':    '智慧能源技术中心',
  '车身·工艺':      '车身',
  '车身 · 工艺':    '车身',
  '设计·HMI':       '智舱',
  '设计 · HMI':     '智舱',
  '质量·海外':      '海外产品质量',
  '质量 · 海外':    '海外产品质量',
  '智舱':           '智舱',
  '底盘':           '底盘',
};
(function migrateDepts() {
  const m = window.MESA_DEPT_MIGRATION;
  (window.MESA_EMPLOYEES || []).forEach((e) => { if (m[e.dept]) e.dept = m[e.dept]; });
  (window.MESA_JOBS || []).forEach((j) => { if (m[j.dept]) j.dept = m[j.dept]; });
})();

// ─────────────────────────── Interviews ───────────────────────────
// 今天 = 2026-05-15（周五）。覆盖：已完成（带 feedback）/ 今日 / 已安排 / 已改期 / 已取消。
window.MESA_INTERVIEW_ROUNDS = ['初筛', '一面', '二面', '终面', 'HR 面', '加面'];

window.MESA_INTERVIEW_STATUS_TONE = {
  '已安排': { bg: '#DBEAFE', fg: '#1D4ED8', dot: '#3B82F6', icon: 'calendar-clock' },
  '进行中': { bg: '#E9E3FF', fg: '#2111A5', dot: '#422AFB', icon: 'video' },
  '已完成': { bg: '#DCFCE7', fg: '#15803D', dot: '#22C55E', icon: 'check-circle-2' },
  '已改期': { bg: '#FEF3C7', fg: '#854D0E', dot: '#EAB308', icon: 'calendar-x' },
  '已取消': { bg: '#FEE2E2', fg: '#B91C1C', dot: '#F53939', icon: 'x-circle' },
};

window.MESA_INTERVIEW_MODE = {
  video:  { label: '视频面试', icon: 'video',  fg: '#422AFB', bg: '#E9E3FF' },
  onsite: { label: '现场面试', icon: 'map-pin', fg: '#15803D', bg: '#DCFCE7' },
  phone:  { label: '电话面试', icon: 'phone-call', fg: '#1D4ED8', bg: '#DBEAFE' },
};

window.MESA_INTERVIEW_RECOMMENDATION = {
  pass:   { label: '建议通过', fg: '#15803D', bg: '#DCFCE7', dot: '#22C55E' },
  hold:   { label: '保留待评估', fg: '#854D0E', bg: '#FEF3C7', dot: '#EAB308' },
  reject: { label: '不通过', fg: '#B91C1C', bg: '#FEE2E2', dot: '#F53939' },
};

window.MESA_INTERVIEWS = [
  // ── 已完成（本周之前 / 本周一二） ──
  {
    id: 'iv-001', candidateId: 'c-003', jobId: 'j-002', round: '一面', date: '2026-05-11', start: '14:00', end: '15:00',
    mode: 'video', location: 'Zoom · https://mesa.zoom.us/j/8826541', interviewers: ['u-002'],
    status: '已完成', createdBy: 'u-001', createdAt: '2026-05-08 11:24',
    notes: '关注实车数据处理与多模态融合经验。',
    feedback: { rating: 4.5, summary: '感知 + 融合知识体系完整，能讲清量产难点。沟通直接，节奏好。', recommendation: 'pass' },
  },
  {
    id: 'iv-002', candidateId: 'c-001', jobId: 'j-001', round: '终面', date: '2026-05-12', start: '10:00', end: '11:30',
    mode: 'onsite', location: '合肥总部 12F · 会议室「黄山」', interviewers: ['u-001', 'u-005'],
    status: '已完成', createdBy: 'u-001', createdAt: '2026-05-09 09:10',
    notes: '海外项目经验交叉验证。',
    feedback: { rating: 4.2, summary: '海外项目深度 OK，质量工具体系扎实；薪资期望偏高需复核。', recommendation: 'pass' },
  },
  {
    id: 'iv-003', candidateId: 'c-006', jobId: 'j-003', round: '一面', date: '2026-05-13', start: '15:30', end: '16:30',
    mode: 'video', location: '飞书会议 · 798-221-336', interviewers: ['u-003'],
    status: '已完成', createdBy: 'u-003', createdAt: '2026-05-10 17:42',
    notes: 'BMS 标定流程与功能安全。',
    feedback: { rating: 3.6, summary: '基础牢固，落地项目偏少；可推进二面看下系统视角。', recommendation: 'hold' },
  },
  {
    id: 'iv-004', candidateId: 'c-005', jobId: 'j-005', round: '二面', date: '2026-05-14', start: '10:30', end: '11:30',
    mode: 'onsite', location: '北京亦庄 R&D · 2F「长城」', interviewers: ['u-005'],
    status: '已完成', createdBy: 'u-005', createdAt: '2026-05-11 09:05',
    notes: '车身工艺案例复盘。',
    feedback: { rating: 3.2, summary: '工艺细节熟悉但跨车型经验不足；与岗位匹配度一般。', recommendation: 'reject' },
  },

  // ── 今天（2026-05-15 周五） ──
  {
    id: 'iv-005', candidateId: 'c-003', jobId: 'j-002', round: '终面', date: '2026-05-15', start: '10:00', end: '11:00',
    mode: 'video', location: 'Zoom · https://mesa.zoom.us/j/9081726354', interviewers: ['u-002', 'u-004'],
    status: '已安排', createdBy: 'u-001', createdAt: '2026-05-12 18:33',
    notes: '终面：业务负责人 + 跨部门 panel。',
    feedback: null,
  },
  {
    id: 'iv-006', candidateId: 'c-009', jobId: 'j-003', round: '二面', date: '2026-05-15', start: '14:30', end: '15:30',
    mode: 'onsite', location: '深圳南山 · 5F「鹏城」', interviewers: ['u-003'],
    status: '已安排', createdBy: 'u-003', createdAt: '2026-05-13 09:48',
    notes: '系统层视角 + 量产标定问题。',
    feedback: null,
  },
  {
    id: 'iv-007', candidateId: 'c-011', jobId: 'j-008', round: '一面', date: '2026-05-15', start: '16:00', end: '17:00',
    mode: 'phone', location: '电话 · 131-4477-2200', interviewers: ['u-004'],
    status: '已安排', createdBy: 'u-001', createdAt: '2026-05-13 11:12',
    notes: '理想 L9 主动悬挂量产经验细聊。',
    feedback: null,
  },

  // ── 下周 / 后续已安排 ──
  {
    id: 'iv-008', candidateId: 'c-007', jobId: 'j-004', round: '终面', date: '2026-05-18', start: '11:00', end: '12:00',
    mode: 'onsite', location: '北京望京 · 8F「未名湖」', interviewers: ['u-001', 'u-002'],
    status: '已安排', createdBy: 'u-001', createdAt: '2026-05-13 14:22',
    notes: '智舱总监终面。',
    feedback: null,
  },
  {
    id: 'iv-009', candidateId: 'c-008', jobId: 'j-006', round: '一面', date: '2026-05-18', start: '15:00', end: '16:00',
    mode: 'video', location: '飞书会议 · 145-872-993', interviewers: ['u-003'],
    status: '已安排', createdBy: 'u-003', createdAt: '2026-05-14 10:05',
    notes: 'HMI Portfolio Review。',
    feedback: null,
  },
  {
    id: 'iv-010', candidateId: 'c-002', jobId: 'j-001', round: '二面', date: '2026-05-19', start: '09:30', end: '10:30',
    mode: 'video', location: 'Zoom · https://mesa.zoom.us/j/5527281234', interviewers: ['u-001'],
    status: '已安排', createdBy: 'u-001', createdAt: '2026-05-14 16:48',
    notes: '量化业绩 / 离职原因复核。',
    feedback: null,
  },
  {
    id: 'iv-011', candidateId: 'c-012', jobId: 'j-007', round: '初筛', date: '2026-05-20', start: '14:00', end: '14:45',
    mode: 'phone', location: '电话 · 187-5566-1100', interviewers: ['u-001'],
    status: '已安排', createdBy: 'u-001', createdAt: '2026-05-14 17:30',
    notes: '高压系统初筛，了解项目深度与跳槽动机。',
    feedback: null,
  },

  // ── 改期 / 取消 ──
  {
    id: 'iv-012', candidateId: 'c-004', jobId: 'j-002', round: '一面', date: '2026-05-16', start: '10:00', end: '11:00',
    mode: 'video', location: '飞书会议 · 631-220-557', interviewers: ['u-002'],
    status: '已改期', createdBy: 'u-002', createdAt: '2026-05-12 13:15',
    notes: '候选人出差，改至下周三。',
    feedback: null,
    reschedule: { from: '2026-05-13 10:00', to: '2026-05-16 10:00', reason: '候选人出差冲突' },
  },
  {
    id: 'iv-013', candidateId: 'c-010', jobId: 'j-008', round: '二面', date: '2026-05-14', start: '16:00', end: '17:00',
    mode: 'onsite', location: '北京亦庄 R&D · 3F「玉渊潭」', interviewers: ['u-004'],
    status: '已取消', createdBy: 'u-004', createdAt: '2026-05-10 12:00',
    notes: '候选人已接 offer，取消流程。',
    feedback: null,
  },
];

// Today, used to compute "today / upcoming / past" buckets in Interviews page.
// Pegged so the canned data lines up with what Dashboard displays.
window.MESA_TODAY = '2026-05-15';
